name: GitHub Actions Demo
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Docker build
              run: |
                  Docker build -t next-class-app .
