name: GitHub Actions Demo
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup AWS ECR Details
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{secrets.AWS_REGION}}
            - name: Login to Amazon ECR
              id: login-pf-aws-ecr
              uses: aws-actions/amazon-ecr-login@v1
            - name: Build and push the tagged docker image to Amazon ECR
              env:
                  ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
                  ECR_REPOSITORY: next-class-app
                  IMAGE_TAG: ${{github.sha}}
                  MAPBOX_API_KEY: ${{secrets.MAPBOX_API_KEY}}
                  CONNECTIONSTRING: ${{secrets.CONNECTIONSTRING}}

              run: |
                  docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --build-arg MAPBOX_API_KEY="$MAPBOX_API_KEY" --build-arg CONNECTIONSTRING="$CONNECTION_STRING" .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            - name: Deploy to AWS Fargate using CDK
              uses: youyo/aws-cdk-github-actions@v2
              with:
                  working_dir: infra
                  cdk_subcommand: deploy
                  cdk_stack: next-class-app
                  cdk_args: "--require-approval never"
                  actions_comment: false
              env:
                  IMAGE_TAG: ${{github.sha}}
